import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} font-sans antialiased`}>
        {/* 웹: 배경색 */}
        <div className="min-h-screen bg-gray-100">
          {/* 모바일 컨테이너: 웹에서 중앙 정렬 + 최대 너비 제한 */}
          <div className="max-w-[430px] mx-auto bg-white min-h-screen shadow-xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
